# Generated by Django 4.2.6 on 2023-11-16 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_comment'),
        ('Main', '0005_post_disliked_by'),
        ('Main', '0005_repost'),
    ]

    operations = [
    ]
