# Generated by Django 4.2.5 on 2023-11-16 04:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0007_post_favorited_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='caption',
            field=models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(limit_value=255, message='Caption must be at most 255 characters.')]),
        ),
    ]
