# Generated by Django 4.2.5 on 2023-11-18 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0005_comment'),
        ('Main', '0007_alter_post_options_post_shared_at_and_more'),
        ('Main', '0008_alter_post_caption'),
    ]

    operations = [
    ]
