# Generated by Django 4.2.6 on 2023-11-21 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0009_merge_20231118_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='shared_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
